name: evde_kutuphane
description: Evde kullanılabilecek basit kütüphane uygulaması (Android, Flutter).
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.6
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  uuid: ^3.0.7
  mobile_scanner: ^3.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
